global using System;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Timers;
global using System.Net;
global using System.Diagnostics;
global using System.Globalization;
global using System.ComponentModel;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Data;
global using System.Windows.Media;
global using System.Windows.Input;
global using System.Windows.Controls;
global using System.Windows.Threading;
global using System.Windows.Navigation;
global using System.Collections.Generic;
global using System.Text.Json;
global using System.Collections.ObjectModel;

global using Timer = System.Timers.Timer;
